name: Deploy to Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: build
        run: |
          pnpm run build
          cd playground
          pnpm run build

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./playground/dist
